language: python

python:
  - '3.6'

addons:
  chrome: stable

branches:
  only:
    - staging

before_script:
  - pip install pipenv
  - pipenv install --dev

before_install:
  - wget https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d chromedriver
  - export DJANGO_SETTINGS_MODULE="purbeurre.travis"

services:
  - postgresql

script:
  - pipenv run python manage.py migrate
  - pipenv run python manage.py test