language: python
dist: bionic

python:
  - '3.6'

addons:
  chrome: stable
  firefox: latest
  postgresql: "11"
  apt:
    packages:
    - postgresql-11

branches:
  only:
    - staging

before_install:
  - wget https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /usr/local/bin

before_script:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - python manage.py test