language: python
dist: xenial

python:
  - '3.6'

addons:
  chrome: stable

branches:
  only:
    - staging

before_script:
  - pip install pipenv
  - pipenv install --dev

before_install:
  - export DJANGO_SETTINGS_MODULE="purbeurre.travis"

services:
  - postgresql

script:
  - pipenv run python manage.py migrate
  - pipenv run python manage.py test