language: python
dist: bionic

python:
  - '3.6'

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - staging

before_install:
  - wget https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /usr/local/bin
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - sudo tar -xvzf geckodriver-v0.26.0-linux64.tar.gz -C /usr/local/bin

before_script:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - python manage.py test