language: python

python:
  - '3.6'

addons:
  chrome: stable

branches:
  only:
    - staging

before_script:
  - pip install pipenv
  - pipenv install --dev

services:
  - postgresql

script:
  - pipenv run python manage.py migrate --settings config.settings.travis
  - pipenv run python manage.py test --settings config.settings.travis