dist: bionic
language: python

python:
  - '3.6'

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt
  - python manage.py install_webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"
    - PATH="$PATH:$(pwd)"

services:
  - postgresql

script:
  - python manage.py test